Update manual.yml

diff --git a/.github/workflows/manual.yml b/.github/workflows/manual.yml
--- a/.github/workflows/manual.yml
+++ b/.github/workflows/manual.yml
@@ -26,14 +26,19 @@ jobs:
           dotnet tool install gitversion.tool -g
           dotnet-gitversion /showvariable SemVer > .version
           cat .version
+          export version=$(cat .version)
+          if [ $version -eq '$(cat .version)' ]
+          then
+            echo "Error!" 1>&2
+            exit 64
+          fi
+          echo '::set-output name=version::$version'
+          echo '$version'
           git config --global user.email "ninja@thesharp.ninja"
           git config --global user.name "GitHub on behalf of Sharp Ninja"
           git stage ./.version
           git commit -m 'Updated `.version`' --allow-empty --status
           git push --repo='https://sharpninja:${{ secrets.GITHUB_TOKEN }}@github.com/sharpninja/Snippets.git'
-          export version='$(cat .version)'
-          echo '::set-output name=version::$version'
-          echo '$version'
 
       - uses: "marvinpinto/action-automatic-releases@latest"
         with:
